# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 333354ad824cc547f34961f12a8db719569839adca7557e28435e36ea8c83b5e1aab7cf910fa16f1e6c33a97e33470cba8e0bd2d314ac22d0d4ce36798bf2caa

test:
  secret_key_base: 4252bb788c1248bc548dd4c46242a162ae3327196e74a43219a534b7affac654e0118ed6909c9077c2042615abbe922df226ff816c1bfba7dbe0f0fa8eff6203

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
